name: Run Custom Tests All dialects

on:
  workflow_call:
    inputs:
      python-versions:
        description: "JSON string of Python versions"
        type: string
        required: true
    secrets:
      READ_LLM_FIXTURES_ROLE:
        required: true
      SF_USERNAME:
        required: true
      SF_PASSWORD:
        required: true
      SF_ACCOUNT:
        required: true
      MYSQL_USERNAME:
        required: true
      MYSQL_PASSWORD:
        required: true
      POSTGRES_USER:
        required: true
      POSTGRES_PASSWORD:
        required: true

jobs:
  custom-tests:
    name: Custom Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}

    # Define services here to run Docker containers alongside your job
    services:
      mysql:
        image: bodoai1/pydough-mysql-tpch:latest
        env:
          # Set environment variables for MySQL container
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: tpch
        ports:
          - 3306:3306

      postgres:
        image: bodoai1/pydough-postgres-tpch:latest
        env:
          # Set environment variables for Postgres container
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: "pydough_test"
        ports:
          - 5432:5432
    env:
      # MYSQL env
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: tpch
      MYSQL_HOST: 127.0.0.1
      # POSTGRES env
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: pydough_test
      POSTGRES_HOST: 127.0.0.1
      # SNOWFLAKE env
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}

    steps:
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.READ_LLM_FIXTURES_ROLE }}
          aws-region: us-east-2
      
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.23"

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -e ".[boto3, snowflake, mysql, postgres]"

      - name: Confirm all connectors are installed
        run: uv run python -c "import boto3; import mysql.connector; import snowflake.connector; import psycopg2; print('All connectors installed')"

      - name: Run Custom Tests for all dialects
        run: uv run pytest -m custom tests/ -rs
